// <auto-generated />
using System;
using FlashcardsAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlashcardsAPI.Migrations
{
    [DbContext(typeof(FlashcardsDbContext))]
    partial class FlashcardsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlashcardsAPI.Domain.Flashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackSide")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FlashcardFolderId")
                        .HasColumnType("integer");

                    b.Property<int>("FolderId")
                        .HasColumnType("integer");

                    b.Property<string>("FrontSide")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMastered")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardFolderId");

                    b.ToTable("Flashcards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackSide = "Rewers1",
                            FolderId = 1,
                            FrontSide = "Awers1",
                            IsMastered = false
                        },
                        new
                        {
                            Id = 2,
                            BackSide = "Rewers2",
                            FolderId = 1,
                            FrontSide = "Awers2",
                            IsMastered = false
                        },
                        new
                        {
                            Id = 3,
                            BackSide = "Rewers3",
                            FolderId = 2,
                            FrontSide = "Awers3",
                            IsMastered = false
                        },
                        new
                        {
                            Id = 4,
                            BackSide = "Rewers4",
                            FolderId = 3,
                            FrontSide = "Awers4",
                            IsMastered = false
                        });
                });

            modelBuilder.Entity("FlashcardsAPI.Domain.FlashcardFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PierwszyFolder"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DrugiFolder"
                        },
                        new
                        {
                            Id = 3,
                            Name = "TrzeciFolder"
                        });
                });

            modelBuilder.Entity("FlashcardsAPI.Domain.Flashcard", b =>
                {
                    b.HasOne("FlashcardsAPI.Domain.FlashcardFolder", null)
                        .WithMany("Flashcards")
                        .HasForeignKey("FlashcardFolderId");
                });

            modelBuilder.Entity("FlashcardsAPI.Domain.FlashcardFolder", b =>
                {
                    b.Navigation("Flashcards");
                });
#pragma warning restore 612, 618
        }
    }
}
